### ISSUE TITLE
Forecast module is unable to retrieve data

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha-modules-extra#32]
The plugin is unable to retrieve data or some reason. I have noticed zWeatherFeed is down [1] not sure if it is related because it seems the service only serves for getting the city ID. query.yahooapis.com [2][3] is the one that is providing the data.

[1] http://www.zazar.net/developers/jquery/zweatherfeed/example_location.html
[2] https://github.com/JeffHoogland/moksha-modules-extra/blob/9ecea3ba9690b96431822f4a1fe8eac4ca90068f/forecasts/src/e_mod_main.c#L387
[3] https://github.com/JeffHoogland/moksha-modules-extra/blob/9ecea3ba9690b96431822f4a1fe8eac4ca90068f/forecasts/src/e_mod_main.c#L635

**Comment by srakitnican** [comment]
Oh never mind, apparently I just needed a re-log. I tend to just suspend the machine.

**Comment by srakitnican** [comment]
This time it not able to retrieve the data no matter what. It just stopped working and even a system reboot does not help. It seems the service is down.

**Comment by rbtylee** [comment]
Due to recent changes in the yahoo weather API the forecast module no longer works: "As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired." It is uncertain when if ever we will get this module back to working. I have been looking at other APIs and have a functioning modification using yr.no working locally. Just not fully satisfied yet and moreover the yr.no API provides less information. Can't really find any good weather APIs that are free,  allow unlimited access/request, and provide more or less as much weather info as the old yahoo one.

So that is where we are at currently....

**Comment by thewaiter** [comment]
Bodhi's forecast module has been rewritten to work with wttr.in weather api. Packages are ready for BL 5.1 as well as BL 6.0 version
